env:
  browser: true
  es2021: true
extends:
  - standard-with-typescript
  - prettier
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.json
plugins:
  - import
rules:
  {
    'import/order':
      ['error', { alphabetize: { order: 'asc' }, 'newlines-between': 'always' }]
  }
root: true
